  push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps + DVC
        run: |
          pip install -r requirements.txt
          pip install dvc

      # ✅ Pull all data + models tracked by DVC
      - name: Pull DVC artifacts
        run: dvc pull

      # ✅ Reproduce pipeline so model exists
      - name: Run DVC pipeline
        run: dvc repro

      # ✅ Debug: verify models folder exists
      - name: List models
        run: ls -R models || echo "models missing"

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/student-api:${{ github.sha }}
